ARG BASE_VERSION=latest
FROM gofunky/readmyhub:${BASE_VERSION}

RUN apk add --no-cache git

ARG BUILD_DATE
ARG VCS_REF

LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vcs-url="https://github.com/gofunky/readmyhub" \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.schema-version="1.0"
