version: '3.7'
services:
  sut:
    build:
      context: ./tests/
      dockerfile: Dockerfile
    environment:
      - DOCKERHUB_USR=${DOCKER_USR}
      - DOCKERHUB_PWD=${DOCKER_PWD}
      - DOCKERHUB_ORG=gofunky
      - DOCKERHUB_REPO=readmyhub
