version: 2.1

orbs:
  orbtools: gofunky/orbtools@0.1.1
  envorb: gofunky/envorb@0.3.5
  docker: gofunky/docker@0.1.2
  #readmyhuborb: gofunky/readmyhub@dev

readmyhub_job: &readmyhub_job
  context: docker-hub
  base_tag: readmyhub
  add_labels: true
  docker_version: 18.09.0
  prepare:
  - run:
      name: Copy README.md
      command: |
        cp -v README.md tests/README.md

master_filter: &master_filter
  filters:
    branches:
      only:
        - master

tag_filter: &tag_filter
  filters:
    tags:
      only: /.*/
    branches:
      ignore: /.*/

pr_filter: &pr_filter
  filters:
    branches:
      ignore:
        - master

workflows:
  test_latest:
    jobs:
      - orbtools/check:
          name: check_pull_request
          <<: *pr_filter

      - docker/build_test:
          name: test_latest
          <<: [*pr_filter, *readmyhub_job]
          tags: "gofunky/readmyhub::latest"

      - docker/build_test:
          name: test_git
          <<: [*pr_filter, *readmyhub_job]
          file: "Dockerfile.git"
          compose: docker-compose.test.git.yml
          tags: "gofunky/readmyhub:git"
          requires: [test_latest]

  build_latest:
    jobs:
      - docker/build_test_push:
          name: build_latest
          <<: [*master_filter, *readmyhub_job]
          tags: "gofunky/readmyhub:latest"
          login: docker login -u $DOCKER_USR -p $DOCKER_PWD

      - docker/build_test_push:
          name: build_git
          <<: [*master_filter, *readmyhub_job]
          file: "Dockerfile.git"
          compose: docker-compose.test.git.yml
          tags: "gofunky/readmyhub:git"
          login: docker login -u $DOCKER_USR -p $DOCKER_PWD
          requires: [build_latest]

      - orbtools/env-pack-publish:
          name: publish_latest_orb
          context: orb-tools
          version: "dev:${CIRCLE_BUILD_NUM}"
          <<: *master_filter

      #- readmyhuborb/update:
      #    name: readme
      #    <<: *master_filter
      #    version: 1.1.0
      #    context: docker-hub
      #    requires: [build_git]

  build_release:
    jobs:
    - envorb/git_tag:
        name: release_tag
        <<: *tag_filter
        alpine_version: "3.8"
        variable: TAG_VERSION

    - docker/build_test_push:
        name: build_release
        <<: [*tag_filter, *readmyhub_job]
        attach: true
        args: "VERSION=${TAG_VERSION}"
        tags: "gofunky/readmyhub:stable,gofunky/readmyhub:${TAG_VERSION}"
        login: docker login -u $DOCKER_USR -p $DOCKER_PWD
        requires: [release_tag]

    - docker/build_test_push:
        name: build_git_release
        <<: [*tag_filter, *readmyhub_job]
        attach: true
        file: "Dockerfile.git"
        args: "BASE_VERSION=${TAG_VERSION}"
        tags: "gofunky/readmyhub:stable-git,gofunky/readmyhub:${TAG_VERSION}-git"
        login: docker login -u $DOCKER_USR -p $DOCKER_PWD
        requires: [release_tag, build_release]

    - orbtools/env-pack-publish:
        name: publish_release_orb
        context: orb-tools
        <<: *tag_filter
        requires: [release_tag]
