version: 2.1

orbs:
  orbtools: gofunky/orbtools@0.3.2
  envorb: gofunky/envorb@0.3.8
  docker: gofunky/docker@0.1.2
  readmyhub: gofunky/readmyhub@dev:168

readmyhub_job: &readmyhub_job
  cache: true
  context: docker-hub
  base_tag: readmyhub
  add_labels: true
  docker_version: 18.09.0
  prepare:
  - run:
      name: Copy README.md
      command: |
        cp -v README.md tests/README.md

master_filter: &master_filter
  filters:
    branches:
      only:
        - master

tag_filter: &tag_filter
  filters:
    tags:
      only: /.*/
    branches:
      ignore: /.*/

pr_filter: &pr_filter
  filters:
    branches:
      ignore:
        - master

use_alpine_version: &use_alpine_version
  alpine_version: "3.8"

workflows:
  test_latest:
    jobs:
      - orbtools/check:
          name: check_pull_request
          <<: [*pr_filter, *use_alpine_version]

      - docker/build_test:
          name: test_latest
          <<: [*pr_filter, *readmyhub_job]
          tags: "gofunky/readmyhub:latest"

      - docker/build_test:
          name: test_git
          <<: [*pr_filter, *readmyhub_job]
          file: "Dockerfile.git"
          compose: docker-compose.test.git.yml
          tags: "gofunky/readmyhub:git"
          add_labels: false
          requires: [test_latest]

      - docker/build_test:
          name: test_envload
          <<: [*pr_filter, *readmyhub_job]
          tags: "gofunky/readmyhub:envload"
          add_labels: false
          path: "./envorb"
          compose: "./envorb/test/docker-compose.test.yml"
          base_tag: envloadtest
          args: "BASE=gofunky/readmyhub:git"
          requires: [test_git]

  build_latest:
    jobs:
      - docker/build_test_push:
          name: build_latest
          <<: [*master_filter, *readmyhub_job]
          tags: "gofunky/readmyhub:latest"
          login: docker login -u $DOCKER_USR -p $DOCKER_PWD

      - docker/build_test_push:
          name: build_git
          <<: [*master_filter, *readmyhub_job]
          file: "Dockerfile.git"
          compose: docker-compose.test.git.yml
          tags: "gofunky/readmyhub:latest-git,gofunky/readmyhub:git"
          login: docker login -u $DOCKER_USR -p $DOCKER_PWD
          add_labels: false
          requires: [build_latest]

      - docker/build_test_push:
          name: build_envload
          <<: [*master_filter, *readmyhub_job]
          tags: "gofunky/readmyhub:latest-envload,gofunky/readmyhub:envload"
          login: docker login -u $DOCKER_USR -p $DOCKER_PWD
          add_labels: false
          path: "./envorb"
          compose: "./envorb/test/docker-compose.test.yml"
          base_tag: envloadtest
          args: "BASE=gofunky/readmyhub:git"
          requires: [build_git]

      - envorb/value:
          name: latest_version
          <<: [*master_filter, *use_alpine_version]
          variable: TAG_VERSION
          value: "latest"

      - orbtools/env-pack-publish:
          name: publish_latest_orb
          context: orb-tools
          version: "dev:${CIRCLE_BUILD_NUM}"
          <<: [*master_filter, *use_alpine_version]
          requires: [latest_version]

      - readmyhub/update:
          name: readme
          <<: *master_filter
          context: docker-hub
          requires: [publish_latest_orb, build_envload]

  build_release:
    jobs:
    - envorb/git_tag:
        name: release_tag
        <<: [*tag_filter, *use_alpine_version]
        variable: TAG_VERSION

    - docker/build_test_push:
        name: build_release
        <<: [*tag_filter, *readmyhub_job]
        attach: true
        args: "VERSION=${TAG_VERSION}"
        tags: "gofunky/readmyhub:stable,gofunky/readmyhub:${TAG_VERSION}"
        login: docker login -u $DOCKER_USR -p $DOCKER_PWD
        requires: [release_tag]

    - docker/build_test_push:
        name: build_git_release
        <<: [*tag_filter, *readmyhub_job]
        attach: true
        file: "Dockerfile.git"
        args: "BASE_VERSION=${TAG_VERSION}"
        tags: "gofunky/readmyhub:stable-git,gofunky/readmyhub:${TAG_VERSION}-git"
        login: docker login -u $DOCKER_USR -p $DOCKER_PWD
        add_labels: false
        requires: [release_tag, build_release]

    - docker/build_test_push:
        name: build_envload_release
        <<: [*tag_filter, *readmyhub_job]
        tags: "gofunky/readmyhub:stable-envload,gofunky/readmyhub:${TAG_VERSION}-envload"
        login: docker login -u $DOCKER_USR -p $DOCKER_PWD
        add_labels: false
        path: "./envorb"
        compose: "./envorb/test/docker-compose.test.yml"
        base_tag: envloadtest
        args: "BASE=gofunky/readmyhub:${TAG_VERSION}-git"
        requires: [build_git_release]

    - orbtools/env-pack-publish:
        name: publish_release_orb
        context: orb-tools
        <<: [*tag_filter, *use_alpine_version]
        version: "${TAG_VERSION}"
        requires: [release_tag, build_envload_release]
