version: 2.1

readmyhub_params: &readmyhub_params
  file:
    description: "Path to the README.md file"
    type: string
    default: "README.md"
  organization:
    description: "Docker Hub organization or user name"
    type: string
    default: ""
  repository:
    description: "Docker Hub repository name"
    type: string
    default: ""

readmyhub_update_params: &readmyhub_update_params
  derive_repo:
    description: "Enable to automatically derive the Docker Hub repository from the GitHub repository"
    type: boolean
    default: true

executors:
  default:
    parameters:
      <<: *readmyhub_params
    docker:
      - image: gofunky/readmyhub:{{TAG_VERSION}}-git
    working_directory: /data
    environment:
      README_PATH: /data/<< parameters.file >>
      IFS: "/"
      DOCKERHUB_ORG: << parameters.organization >>
      DOCKERHUB_REPO: << parameters.repository >>
commands:
  update:
    parameters:
      <<: *readmyhub_update_params
    steps:
      - checkout
      - run:
          name: Check DOCKER_USR
          command: |
            if [ -z "$DOCKER_USR" ]; then
              echo "ERROR: DOCKER_USR is not set!"
              exit 127
            fi
      - run:
          name: Check DOCKER_PWD
          command: |
            if [ -z "$DOCKER_PWD" ]; then
              echo "ERROR: DOCKER_PWD is not set!"
              exit 127
            fi
      - when:
          condition: << parameters.derive_repo >>
          steps:
            - run:
                name: Update README
                command: |
                  set -f
                  URL=`git remote get-url origin`
                  URL=`echo "$URL" | sed -e "s/^https:\/\///" -e "s/\.git//" | sed -e "s/^git@//"`
                  URL=`echo "$URL" | sed -r 's/github.com:/github.com\//g'`
                  set -- $URL
                  DOCKERHUB_ORG=$2
                  DOCKERHUB_REPO=$3
                  export DOCKERHUB_USR=${DOCKER_USR}
                  export DOCKERHUB_PWD=${DOCKER_PWD}
                  node /app/index.js
                  set +f
      - unless:
          condition: << parameters.derive_repo >>
          steps:
            - run:
                name: Update README
                command: |
                  export DOCKERHUB_USR=${DOCKER_USR}
                  export DOCKERHUB_PWD=${DOCKER_PWD}
                  node /app/index.js
jobs:
  update:
    description: "Push the given README.md to the Docker Hub"
    executor:
      name: default
      file: << parameters.file >>
      organization: << parameters.organization >>
      repository: << parameters.repository >>
    parameters:
      <<: *readmyhub_params
      <<: *readmyhub_update_params
    steps:
      - update:
          derive_repo: << parameters.derive_repo >>
