version: 2.1

description: Allows you to push README.md files to the Docker Hub.

orbs:
  envorb: gofunky/envorb@0.3.9

readmyhub_params: &readmyhub_params
  file:
    description: "Path to the README.md file"
    type: string
    default: "README.md"

readmyhub_update_params: &readmyhub_update_params
  organization:
    description: >
      Docker Hub organization or user name.
      Environment variables from envorbs are accepted.
      By default, the git organization is assumed.
    type: string
    default: ""
  repository:
    description: >
      Docker Hub repository name.
      Environment variables from envorbs are accepted.
      By default, the git repository name is assumed.
    type: string
    default: ""

executors:
  default:
    parameters:
      <<: *readmyhub_params
    docker:
      - image: gofunky/readmyhub:{{.TAG_VERSION}}-envload
    working_directory: /data
    environment:
      README_PATH: /data/<< parameters.file >>

commands:
  update:
    parameters:
      <<: *readmyhub_update_params
    steps:
      - run:
          name: Check DOCKER_USR
          command: |
            if [ -z "$DOCKER_USR" ]; then
              echo "ERROR: DOCKER_USR is not set!"
              exit 127
            fi
      - run:
          name: Check DOCKER_PWD
          command: |
            if [ -z "$DOCKER_PWD" ]; then
              echo "ERROR: DOCKER_PWD is not set!"
              exit 127
            fi
      - when:
          condition: << parameters.organization >>
          steps:
            - envorb/value:
                variable: DOCKERHUB_ORG
                value: << parameters.organization >>
      - unless:
          condition: << parameters.organization >>
          steps:
            - envorb/git_org:
                variable: DOCKERHUB_ORG
      - when:
          condition: << parameters.repository >>
          steps:
            - envorb/value:
                variable: DOCKERHUB_REPO
                value: << parameters.repository >>
      - unless:
          condition: << parameters.repository >>
          steps:
            - envorb/git_name:
                variable: DOCKERHUB_REPO
      - run:
          name: Upload README
          command: |
            source /usr/local/bin/envload
            export DOCKERHUB_USR=${DOCKER_USR}
            export DOCKERHUB_PWD=${DOCKER_PWD}
            node /app/index.js

jobs:
  update:
    description: "Push the given README.md to the Docker Hub"
    executor:
      name: default
      file: << parameters.file >>
      organization: << parameters.organization >>
      repository: << parameters.repository >>
    parameters:
      <<: [*readmyhub_params, *readmyhub_update_params]
    steps:
      - checkout
      - update:
          organization: << parameters.organization >>
          repository: << parameters.repository >>
